Jordan:  # Riders Name
  R03: 
    Desc: 'Baseline'
    ValidLaps: [3,4,5,6,7,8,9,10,11]
  R04:  
    Desc: 'Baseline'
    ValidLaps: [3,4,5,6,7,8,9]
  R05:  
    Desc: 'Rod'
    ValidLaps: [3,4,5,6,7,8,9,10]
  R06:  
    Desc: '50mm Disc'
    ValidLaps: [3,4,5,6,7]
  R07:  
    Desc: '60mm Disc'
    ValidLaps: [6,7,8]
  R08:  
    Desc: '80mm Disc'
    ValidLaps: [3,4,5,6,7,8,9]
  R09:  
    Desc: '100mm Disc'
    ValidLaps: [3,4,5,6,7,8]
  R10:  
    Desc: 'Shuffle'
    ValidLaps: [3,4,5,6,7,8,9,10,11]


