- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

#- name: "Aero Analysis"
#  url: "https://windcheetah.net/"
#  title: "Wind Cheetah Aero Analysis Service"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
